# Generated by Django 3.1.6 on 2021-03-03 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AkunModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akun', models.IntegerField(blank=True, null=True)),
                ('pegawai', models.IntegerField(blank=True, null=True)),
                ('jenis_akun', models.CharField(choices=[('pegawai', 'Pegawai'), ('operator', 'Operator'), ('admin', 'Administrator')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BerkalaHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('kgb_nomor', models.CharField(max_length=255)),
                ('kgb_tanggal', models.DateField(auto_now=True)),
                ('tmt', models.DateField(blank=True, null=True)),
                ('tmt_baru', models.DateField(blank=True, null=True)),
                ('golongan', models.CharField(max_length=5)),
                ('pejabat_ttd', models.CharField(default='GUBERNUR JAMBI', max_length=255)),
                ('masa_kerja_tahun', models.IntegerField(blank=True, null=True)),
                ('masa_kerja_bulan', models.IntegerField(blank=True, null=True)),
                ('kgb_image', models.FileField(blank=True, null=True, upload_to='media')),
                ('masa_kerjabaru_tahun', models.IntegerField(blank=True, null=True)),
                ('masa_kerjabaru_bulan', models.IntegerField(blank=True, null=True)),
                ('nilai', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GajiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa_kerja', models.IntegerField()),
                ('golongan', models.CharField(max_length=5)),
                ('tbgaji_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('terbilang', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JabatanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=15)),
                ('bup', models.IntegerField()),
                ('jenjang', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OpdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kepala_opd', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PangkatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nilai', models.IntegerField()),
                ('simbol', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PegawaiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.IntegerField(null=True)),
                ('nip', models.CharField(max_length=100, null=True)),
                ('opd', models.IntegerField(blank=True, null=True)),
                ('pangkat', models.IntegerField(null=True)),
                ('pengguna', models.IntegerField(blank=True, null=True)),
                ('alamat', models.CharField(max_length=255)),
                ('telpon', models.CharField(max_length=30)),
                ('gaji_skrg', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
