# Generated by Django 3.1.6 on 2021-02-24 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BerkalaHistoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('kgb_nomor', models.CharField(max_length=255)),
                ('kgb_tanggal', models.DateField(auto_now=True)),
                ('tmt', models.DateField(blank=True, null=True)),
                ('tmt_baru', models.DateField(blank=True, null=True)),
                ('golongan', models.CharField(max_length=5)),
                ('pejabat_ttd', models.CharField(default='GUBERNUR JAMBI', max_length=255)),
                ('masa_kerja_tahun', models.IntegerField(blank=True, null=True)),
                ('masa_kerja_bulan', models.IntegerField(blank=True, null=True)),
                ('kgb_image', models.FileField(blank=True, null=True, upload_to='media')),
                ('masa_kerjabaru_tahun', models.IntegerField(blank=True, null=True)),
                ('masa_kerjabaru_bulan', models.IntegerField(blank=True, null=True)),
                ('nilai', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GajiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masa_kerja', models.IntegerField()),
                ('golongan', models.CharField(max_length=5)),
                ('tbgaji_currency', models.CharField(blank=True, max_length=255, null=True)),
                ('terbilang', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JabatanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis', models.CharField(max_length=15)),
                ('bup', models.IntegerField()),
                ('jenjang', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='OpdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kepala_opd', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PangkatModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nilai', models.IntegerField()),
                ('simbol', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PegawaiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.IntegerField(null=True)),
                ('nip', models.CharField(max_length=100, null=True)),
                ('pangkat', models.IntegerField(null=True)),
                ('alamat', models.CharField(max_length=255)),
                ('telpon', models.CharField(max_length=15)),
                ('gaji_skrg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.gajimodel')),
                ('opd', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pegawai.opdmodel')),
                ('pengguna', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
