# Generated by Django 3.1.6 on 2021-03-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akunmodel',
            name='akun',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='akunmodel',
            name='pegawai',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
