# Generated by Django 3.1.6 on 2021-03-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegawai', '0002_auto_20210303_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaimodel',
            name='gaji_skrg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegawaimodel',
            name='jabatan',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pegawaimodel',
            name='opd',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pegawaimodel',
            name='pangkat',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pegawaimodel',
            name='pengguna',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
